import "server-only";

import PDFDocument from "pdfkit";
import { formatMinutes } from "@/lib/project-stats";
import type { WorkSummary } from "@/lib/work-summary";

const dateFmt = new Intl.DateTimeFormat("en-GB", {
  day: "2-digit",
  month: "short",
  year: "numeric",
});

// Renders a work summary to a PDF and resolves with the bytes.
export function renderWorkSummaryPdf(summary: WorkSummary): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: "A4", margin: 56 });
    const chunks: Buffer[] = [];
    doc.on("data", (chunk) => chunks.push(chunk as Buffer));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    doc
      .fillColor("#0b57d0")
      .fontSize(22)
      .font("Helvetica-Bold")
      .text("Workjournal — Work summary");
    doc.moveDown(0.3);
    doc
      .fillColor("#444746")
      .fontSize(11)
      .font("Helvetica")
      .text(
        `${summary.personName}  ·  ${dateFmt.format(summary.from)} – ${dateFmt.format(summary.to)}`,
      );
    doc
      .moveTo(56, doc.y + 6)
      .lineTo(539, doc.y + 6)
      .strokeColor("#c4c7c5")
      .stroke();
    doc.moveDown(1);

    // Totals
    doc
      .fillColor("#1f1f1f")
      .fontSize(13)
      .font("Helvetica-Bold")
      .text("Overview");
    doc.moveDown(0.3);
    doc
      .fontSize(11)
      .font("Helvetica")
      .fillColor("#1f1f1f")
      .text(
        `Total time logged: ${formatMinutes(summary.totalMinutes)}  ·  ${summary.entryCount} entries  ·  ${summary.projects.length} projects`,
      );
    doc.moveDown(1);

    // Narrative summary
    doc.fontSize(13).font("Helvetica-Bold").text("Summary");
    doc.moveDown(0.3);
    doc.fontSize(11).font("Helvetica");
    for (const sentence of summary.sentences) {
      doc.fillColor("#1f1f1f").text(sentence, { align: "left" });
      doc.moveDown(0.4);
    }
    doc.moveDown(0.6);

    // Per-project breakdown
    if (summary.projects.length > 0) {
      doc.fontSize(13).font("Helvetica-Bold").fillColor("#1f1f1f");
      doc.text("Projects");
      doc.moveDown(0.4);
      for (const project of summary.projects) {
        doc
          .fontSize(11.5)
          .font("Helvetica-Bold")
          .fillColor("#0b57d0")
          .text(
            `${project.name}${project.completed ? " (completed)" : ""} — ${formatMinutes(project.minutes)}`,
          );
        doc.font("Helvetica").fontSize(10.5).fillColor("#444746");
        if (project.entryTitles.length > 0) {
          doc.text(`Entries: ${project.entryTitles.join(", ")}`);
        }
        if (project.blockers.length > 0) {
          doc.text(`Blockers: ${project.blockers.join("; ")}`);
        }
        doc.moveDown(0.6);
      }
    }

    doc.moveDown(1);
    doc
      .fontSize(8)
      .fillColor("#747775")
      .text(
        `Generated by Workjournal Tool on ${dateFmt.format(new Date())}.`,
        { align: "center" },
      );

    doc.end();
  });
}
